import { describe, expect, it } from "vitest";
import { structuralScore } from "../src/structural.js";
import type { TestPlan, Scenario, CapabilitySubgraph } from "@forge/core";

const mockSubgraph: CapabilitySubgraph = {
  states: [
    {
      id: "st_1",
      signature: "sig1",
      url: "/checkout",
      title: "Checkout",
      snapshotYaml: "",
    },
    {
      id: "st_2",
      signature: "sig2",
      url: "/checkout/payment",
      title: "Payment",
      snapshotYaml: "",
    },
    {
      id: "st_3",
      signature: "sig3",
      url: "/order/123",
      title: "Order Confirmed",
      snapshotYaml: "",
    },
  ],
  transitions: [
    {
      id: "tr_1",
      sessionId: "ses_1",
      fromStateId: "st_1",
      toStateId: "st_2",
      viaAffordanceId: "af_1",
      action: "click",
      observedAt: "2026-01-01T00:00:00Z",
    },
    {
      id: "tr_2",
      sessionId: "ses_1",
      fromStateId: "st_2",
      toStateId: "st_3",
      viaAffordanceId: "af_2",
      action: "click",
      observedAt: "2026-01-01T00:00:00Z",
    },
    {
      id: "tr_3",
      sessionId: "ses_1",
      fromStateId: "st_1",
      toStateId: "st_1",
      viaAffordanceId: "af_3",
      action: "click",
      observedAt: "2026-01-01T00:00:00Z",
    },
  ],
  affordances: [
    {
      id: "af_1",
      stateId: "st_1",
      ref: "e1",
      role: "button",
      accessibleName: "Continue",
      kind: "button",
      enabled: true,
      destructive: false,
      observedNotExercised: false,
      notExercisedReason: null,
      bbox: null,
    },
    {
      id: "af_2",
      stateId: "st_2",
      ref: "e2",
      role: "button",
      accessibleName: "Place order",
      kind: "button",
      enabled: true,
      destructive: false,
      observedNotExercised: false,
      notExercisedReason: null,
      bbox: null,
    },
    {
      id: "af_3",
      stateId: "st_1",
      ref: "e3",
      role: "textbox",
      accessibleName: "Card number",
      kind: "textbox",
      enabled: true,
      destructive: false,
      observedNotExercised: false,
      notExercisedReason: null,
      bbox: null,
    },
    {
      id: "af_4",
      stateId: "st_1",
      ref: "e4",
      role: "button",
      accessibleName: "Cancel order",
      kind: "button",
      enabled: true,
      destructive: true,
      observedNotExercised: true,
      notExercisedReason: "DENY_LIST",
      bbox: null,
    },
  ],
  entryStateId: "st_1",
  exitConditions: ["Order Confirmed reached"],
  subgraphTruncated: false,
};

function makePlan(scenarios: Partial<Scenario>[]): TestPlan {
  return {
    id: "pln_1",
    lapId: "lap_1",
    capabilityId: "cap_1",
    round: 0,
    scenarios: scenarios.map((s, i) => ({
      id: `SC-${String(i + 1).padStart(3, "0")}`,
      planId: "pln_1",
      title: s.title ?? `Scenario ${i + 1}`,
      class: s.class ?? "happy",
      priority: "P0",
      priorityReason: "test",
      preconditions: [],
      steps: s.steps ?? [],
      expectedOutcome: s.expectedOutcome ?? "outcome",
      source: "agent",
      sourceRefs: [],
      plannedNotGenerated: false,
      notGeneratedReason: null,
      version: 1,
    })) as Scenario[],
    markdownPath: "plans/test.md",
    createdAt: "2026-01-01T00:00:00Z",
  };
}

describe("structuralScore", () => {
  it("computes perfect score when all terms covered", () => {
    const plan = makePlan([
      {
        class: "happy",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open checkout",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "fill",
            targetIntent: "enter card",
            stateId: "st_1",
            affordanceRef: "e3",
            locator: null,
            input: "4242",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "click",
            targetIntent: "continue",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s3",
            order: 3,
            kind: "click",
            targetIntent: "place order",
            stateId: "st_2",
            affordanceRef: "e2",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s4",
            order: 4,
            kind: "assertText",
            targetIntent: "confirm order",
            stateId: "st_3",
            affordanceRef: null,
            locator: null,
            input: "Order confirmed",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
      {
        class: "negative",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open checkout",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "click",
            targetIntent: "submit empty",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "assertUrl",
            targetIntent: "stay on page",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "/checkout",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
      {
        class: "boundary",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open checkout",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "fill",
            targetIntent: "max card length",
            stateId: "st_1",
            affordanceRef: "e3",
            locator: null,
            input: "12345678901234567890",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "assertText",
            targetIntent: "error shown",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "Invalid",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
      {
        class: "error_state",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open checkout",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "fill",
            targetIntent: "expired card",
            stateId: "st_2",
            affordanceRef: "e3",
            locator: null,
            input: "4000",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "click",
            targetIntent: "place order",
            stateId: "st_2",
            affordanceRef: "e2",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s3",
            order: 3,
            kind: "assertText",
            targetIntent: "decline shown",
            stateId: "st_2",
            affordanceRef: null,
            locator: null,
            input: "Declined",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
    ]);

    const result = structuralScore(plan, mockSubgraph);
    expect(result.score).toBeGreaterThanOrEqual(0.7);
    expect(result.affordanceCoverage).toBe(1.0); // 3 eligible, all 3 cited
    expect(result.classCoverage).toBe(1.0); // all 4 classes
  });

  it("excludes destructive affordances from denominator", () => {
    const plan = makePlan([
      {
        class: "happy",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "click",
            targetIntent: "place",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "assertText",
            targetIntent: "confirm",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "ok",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
    ]);

    const result = structuralScore(plan, mockSubgraph);
    // eligible: e1, e2, e3 (3) - e4 is destructive
    // cited: e1 only
    expect(result.details.affordances.eligible).toBe(3);
    expect(result.details.affordances.cited).toBe(1);
    expect(result.affordanceCoverage).toBeCloseTo(1 / 3, 2);
  });

  it("counts distinct affordances, not steps", () => {
    const plan = makePlan([
      {
        class: "happy",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "click",
            targetIntent: "continue",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "click",
            targetIntent: "continue again",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s3",
            order: 3,
            kind: "click",
            targetIntent: "continue again",
            stateId: "st_1",
            affordanceRef: "e1",
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s4",
            order: 4,
            kind: "assertText",
            targetIntent: "confirm",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "ok",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
    ]);

    const result = structuralScore(plan, mockSubgraph);
    expect(result.details.affordances.cited).toBe(1);
  });

  it("assertion density saturates at 2 per scenario", () => {
    const plan = makePlan([
      {
        class: "happy",
        steps: [
          {
            id: "s0",
            order: 0,
            kind: "navigate",
            targetIntent: "open",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: null,
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s1",
            order: 1,
            kind: "assertText",
            targetIntent: "a",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "a",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s2",
            order: 2,
            kind: "assertText",
            targetIntent: "b",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "b",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
          {
            id: "s3",
            order: 3,
            kind: "assertText",
            targetIntent: "c",
            stateId: "st_1",
            affordanceRef: null,
            locator: null,
            input: "c",
            timeoutMs: 5000,
            optional: false,
            fingerprintId: null,
            resolvedCount: null,
          },
        ],
      },
    ]);

    const result = structuralScore(plan, mockSubgraph);
    expect(result.assertionDensity).toBe(1.0); // 3 assertions, max 2*1=2 -> min(1, 3/2) = 1
  });

  it("empty subgraph denominators score 1.0", () => {
    const emptySubgraph: CapabilitySubgraph = {
      states: [],
      transitions: [],
      affordances: [],
      entryStateId: "st_1",
      exitConditions: [],
    };

    const plan = makePlan([]);
    const result = structuralScore(plan, emptySubgraph);
    expect(result.transitionCoverage).toBe(1.0);
    expect(result.stateCoverage).toBe(1.0);
    expect(result.affordanceCoverage).toBe(1.0);
  });
});
