import { describe, expect, it } from "vitest";
import {
  Affordance,
  Capability,
  CapabilityMap,
  CoverageAssessment,
  Diagnosis,
  ElementFingerprint,
  Evidence,
  Gap,
  HealCandidate,
  Lap,
  QualityReport,
  RobustnessScore,
  Run,
  Scenario,
  Session,
  SessionEvent,
  SessionInput,
  State,
  TestPatch,
  TestPlan,
  TestStep,
  Transition,
} from "./index.js";

const at = "2026-01-01T00:00:00.000Z";
const ids = {
  session: "ses_01j9x2k4",
  state: "st_01j9x2k5",
  affordance: "af_01j9x2k6",
  transition: "tr_01j9x2k7",
  capability: "cap_01j9x2k8",
  lap: "lap_01j9x2k9",
  plan: "pln_01j9x3a0",
  assessment: "cva_01j9x3a1",
  gap: "gap_01j9x3a2",
  run: "run_01j9x3aa",
  evidence: "ev_01j9x3ab",
  fingerprint: "fp_01j9x3ac",
  diagnosis: "dg_01j9x3ad",
  candidate: "hc_01j9x3ae",
  patch: "pt_01j9x3af",
  report: "qr_01j9x3ag",
} as const;

const affordance = {
  id: ids.affordance,
  stateId: ids.state,
  ref: "e42",
  role: "button",
  accessibleName: "Submit order",
  kind: "button",
  bbox: { x: 10, y: 20, w: 100, h: 40 },
};

const state = {
  id: ids.state,
  sessionId: ids.session,
  signature: "0123456789abcdef",
  url: "https://shop.test/checkout",
  title: "Checkout",
  snapshotEvidenceId: ids.evidence,
  affordanceIds: [ids.affordance],
  discoveredAt: at,
};

const factors = {
  authProximity: 1,
  dataMutation: 0.8,
  moneyOrPii: 1,
  graphCentrality: 0.5,
  affordanceDensity: 0.4,
  statedIntent: 1,
};

const capability = {
  id: ids.capability,
  sessionId: ids.session,
  name: "Checkout",
  description: "Complete an order checkout flow",
  entryStateId: ids.state,
  stateIds: [ids.state],
  exitConditions: ["Order confirmation is visible"],
  risk: { score: 0.9, factors },
  priorityRank: 0,
};

const step = {
  id: "s1",
  order: 0,
  kind: "click",
  targetIntent: "Submit the order",
  stateId: ids.state,
  affordanceRef: "e42",
  locator: null,
  input: null,
};

const scenario = {
  id: "SC-001",
  planId: ids.plan,
  title: "Submit checkout successfully",
  class: "happy",
  priority: "P0",
  priorityReason: "Revenue path",
  steps: [step],
  expectedOutcome: "Order confirmation appears",
};

const gap = {
  id: ids.gap,
  class: "MISSING_EDGE_CASE",
  title: "Missing declined payment",
  why: "The payment error branch is not covered",
  severity: "MAJOR",
  suggestedScenario: "Submit a declined payment method",
};

const score = {
  current: 50,
  projected: 80,
  components: { coverage: 50 },
  perCapability: [
    {
      capabilityId: ids.capability,
      name: "Checkout",
      points: 50,
      lostBecause: ["Missing error branch"],
    },
  ],
  findings: [{ findingId: ids.gap, title: "Missing branch", pointsIfFixed: 30 }],
};

const cases: ReadonlyArray<readonly [string, { parse(value: unknown): unknown }, unknown]> = [
  ["SessionInput", SessionInput, { url: "https://shop.test" }],
  [
    "Session",
    Session,
    {
      id: ids.session,
      input: { url: "https://shop.test" },
      status: "CREATED",
      exitCode: null,
      createdAt: at,
      finishedAt: null,
      usage: null,
    },
  ],
  ["Affordance", Affordance, affordance],
  ["State", State, state],
  [
    "Transition",
    Transition,
    {
      id: ids.transition,
      sessionId: ids.session,
      fromStateId: ids.state,
      toStateId: ids.state,
      viaAffordanceId: ids.affordance,
      action: "click",
      observedAt: at,
    },
  ],
  ["Capability", Capability, capability],
  [
    "CapabilityMap",
    CapabilityMap,
    {
      sessionId: ids.session,
      authenticated: false,
      states: [state],
      affordances: [affordance],
      transitions: [],
      capabilities: [capability],
      frontier: { discovered: 1, explored: 1, haltReason: "EXHAUSTED" },
    },
  ],
  ["TestStep", TestStep, step],
  ["Scenario", Scenario, scenario],
  [
    "TestPlan",
    TestPlan,
    {
      id: ids.plan,
      lapId: ids.lap,
      capabilityId: ids.capability,
      round: 0,
      scenarios: [scenario],
      markdownPath: "plans/checkout.md",
      createdAt: at,
    },
  ],
  ["Gap", Gap, gap],
  [
    "CoverageAssessment",
    CoverageAssessment,
    {
      id: ids.assessment,
      lapId: ids.lap,
      planId: ids.plan,
      round: 0,
      score: 0.8,
      floor: 0.7,
      structural: {
        affordancesExercised: 1,
        affordancesTotal: 1,
        transitionsTraversed: 0,
        transitionsTotal: 0,
        statesReached: 1,
        statesTotal: 1,
        classesPresent: ["happy"],
      },
      gaps: [gap],
      verdict: "PASS",
      source: "deterministic",
      createdAt: at,
    },
  ],
  [
    "Lap",
    Lap,
    {
      id: ids.lap,
      sessionId: ids.session,
      capabilityId: ids.capability,
      index: 0,
      status: "LAP_PENDING",
      outcome: null,
      replanRounds: 0,
      healAttempts: {},
      specPath: null,
      startedAt: at,
      bankedAt: null,
    },
  ],
  [
    "Run",
    Run,
    {
      id: ids.run,
      lapId: ids.lap,
      scenarioId: "SC-001",
      status: "QUEUED",
      attempt: 0,
      startedAt: at,
      finishedAt: null,
      durationMs: null,
      verification: {},
      diagnosisSource: null,
    },
  ],
  [
    "SessionEvent",
    SessionEvent,
    {
      seq: 0,
      sessionId: ids.session,
      lapId: null,
      at,
      actor: "orchestrator",
      type: "session.started",
      payload: {},
    },
  ],
  [
    "Evidence",
    Evidence,
    {
      id: ids.evidence,
      sessionId: ids.session,
      lapId: null,
      runId: null,
      stepId: null,
      type: "SNAPSHOT",
      path: `sessions/${ids.session}/evidence/${ids.evidence}-0123456789ab.json`,
      sha256: "a".repeat(64),
      bytes: 12,
      capturedAt: at,
      label: "Entry snapshot",
    },
  ],
  [
    "Diagnosis",
    Diagnosis,
    {
      id: ids.diagnosis,
      runId: ids.run,
      stepId: "s1",
      kind: "LOCATOR_BREAK",
      confidence: 0.9,
      evidenceIds: [ids.evidence, "ev_01j9x3bb", "ev_01j9x3cb"],
      explanation: "The original locator no longer resolves",
      recommendedAction: "HEAL",
      source: "deterministic",
      failureSignature: "0123456789abcdef",
    },
  ],
  [
    "HealCandidate",
    HealCandidate,
    {
      id: ids.candidate,
      diagnosisId: ids.diagnosis,
      rank: 0,
      strategy: "role_name",
      locator: "getByRole('button')",
      resolvedCount: 1,
      signals: {
        semantic: 1,
        role: 1,
        text: 1,
        domContext: 0.9,
        visualGeometry: 0.8,
        historical: 0,
      },
      score: 0.88,
      rationale: "Same observed role and accessible name",
    },
  ],
  [
    "TestPatch",
    TestPatch,
    {
      id: ids.patch,
      runId: ids.run,
      scenarioId: "SC-001",
      stepId: "s1",
      before: "#submit",
      after: "getByRole('button')",
      diff: "--- before\n+++ after",
      beforeFileSha256: "b".repeat(64),
      appliedAt: at,
      verifiedAt: null,
      revertedAt: null,
    },
  ],
  [
    "ElementFingerprint",
    ElementFingerprint,
    {
      id: ids.fingerprint,
      scenarioId: "SC-001",
      stepId: "s1",
      capturedInRunId: ids.run,
      capturedAt: at,
      intent: "Submit the order",
      role: "button",
      accessibleName: "Submit order",
      text: "Submit",
      tagName: "button",
      testId: null,
      attributes: { type: "submit" },
      ancestorPath: [{ tag: "form", role: null, id: "checkout" }],
      siblingIndex: 0,
      bbox: { x: 10, y: 20, w: 100, h: 40 },
      viewport: {},
      screenshotCropEvidenceId: null,
      computedStyle: {
        color: "rgb(0,0,0)",
        backgroundColor: "rgb(255,255,255)",
        fontSize: "16px",
        fontWeight: "400",
        display: "block",
        visibility: "visible",
      },
    },
  ],
  ["RobustnessScore", RobustnessScore, score],
  [
    "QualityReport",
    QualityReport,
    {
      id: ids.report,
      sessionId: ids.session,
      scenariosCovered: [
        {
          scenarioId: "SC-001",
          capability: "Checkout",
          title: "Submit checkout successfully",
          class: "happy",
          priority: "P0",
        },
      ],
      outcomes: { passed: 1, failed: 0, healed: 0, flaky: 0, skipped: 0 },
      healerActions: [],
      coverageGapsRemaining: [gap],
      untestedFlowRisk: [
        {
          capabilityId: ids.capability,
          name: "Checkout",
          why: "One payment branch remains untested",
          riskScore: 0.8,
          factors,
        },
      ],
      defects: [],
      score,
      hoursSaved: null,
      generatedAt: at,
    },
  ],
];

describe("schema round trips", () => {
  for (const [name, schema, value] of cases) {
    it(`${name} survives a JSON round trip`, () => {
      const parsed = schema.parse(JSON.parse(JSON.stringify(value)) as unknown);
      expect(schema.parse(JSON.parse(JSON.stringify(parsed)) as unknown)).toEqual(parsed);
    });
  }
});
