import type { ValidatedSuite, ValidatedScenario } from "./types.js";
import fs from "node:fs/promises";
import path from "node:path";

export async function emitProject(
  suite: ValidatedSuite,
  outDir: string,
): Promise<{ files: string[]; manifest: Record<string, unknown> }> {
  await fs.mkdir(outDir, { recursive: true });

  const files: string[] = [];
  const manifest: Record<string, unknown> = {
    sessionId: suite.provenance.sessionId,
    planId: suite.provenance.planId,
    modelId: suite.provenance.modelId,
    browserRevision: suite.provenance.browserRevision,
    timestamp: suite.provenance.timestamp,
    capability: suite.capabilityName,
    scenarios: suite.scenarios.map((s) => s.id),
  };

  // Write package.json
  const packageJson = {
    name: "forge-generated-tests",
    version: "1.0.0",
    private: true,
    scripts: {
      test: "playwright test",
      "test:headed": "playwright test --headed",
    },
    devDependencies: {
      "@playwright/test": "^1.52.0",
    },
  };
  await writeFile(
    path.join(outDir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );
  files.push("package.json");

  // Write playwright.config.ts
  const playwrightConfig = `import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    baseURL: process.env.FORGE_BASE_URL ?? "http://localhost:3000",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    command: "echo 'External server expected'",
    url: "http://localhost:3000",
    reuseExistingServer: true,
    timeout: 120000,
  },
});`;
  await writeFile(path.join(outDir, "playwright.config.ts"), playwrightConfig);
  files.push("playwright.config.ts");

  // Write README.md
  const readme = `# Generated Test Suite

This test suite was generated by FORGE.

**Capability:** ${suite.capabilityName}
**Plan:** ${suite.planId} (round ${suite.round})
**Generated:** ${suite.provenance.timestamp}

## Scenarios

${suite.scenarios.map((s) => `- [${s.id}] ${s.title} (${s.class}, ${s.priority})`).join("\n")}

## Running

\`\`\`bash
npm install
npx playwright test
\`\`\`

Set \`FORGE_BASE_URL\` to the target application URL.
`;
  await writeFile(path.join(outDir, "README.md"), readme);
  files.push("README.md");

  // Write forge.manifest.json
  await writeFile(
    path.join(outDir, "forge.manifest.json"),
    JSON.stringify(manifest, null, 2),
  );
  files.push("forge.manifest.json");

  // Write .gitignore
  const gitignore = `.auth/
test-results/
playwright-report/
node_modules/
*.local
`;
  await writeFile(path.join(outDir, ".gitignore"), gitignore);
  files.push(".gitignore");

  // Write tests/fixtures/forge.ts
  await fs.mkdir(path.join(outDir, "tests", "fixtures"), { recursive: true });
  const fixtures = `import { test as base, type Page } from "@playwright/test";

export const test = base.extend<{
  forgePage: Page;
}>();

export { expect } from "@playwright/test";
`;
  await writeFile(path.join(outDir, "tests", "fixtures", "forge.ts"), fixtures);
  files.push("tests/fixtures/forge.ts");

  // Write auth.setup.ts
  const authSetup = `import { test as setup, expect } from "@playwright/test";

setup("authenticate", async ({ page }) => {
  const username = process.env.FORGE_USER;
  const password = process.env.FORGE_PASS;
  if (!username || !password) {
    throw new Error("FORGE_USER and FORGE_PASS must be set");
  }
  
  await page.goto("/login");
  await page.getByRole("textbox", { name: "Email" }).fill(username);
  await page.getByRole("textbox", { name: "Password" }).fill(password);
  await page.getByRole("button", { name: "Sign in" }).click();
  
  await expect(page.getByRole("link", { name: /logout|sign out/i })).toBeVisible();
  
  await page.context().storageState({ path: ".auth/state.json" });
});`;
  await fs.mkdir(path.join(outDir, "tests"), { recursive: true });
  await writeFile(path.join(outDir, "tests", "auth.setup.ts"), authSetup);
  files.push("tests/auth.setup.ts");

  // Write generated test files
  const generatedDir = path.join(outDir, "tests", "generated");
  await fs.mkdir(generatedDir, { recursive: true });

  for (const scenario of suite.scenarios) {
    const testFile = generateTestFile(scenario, suite);
    const fileName = `${suite.capabilityName.toLowerCase().replace(/\s+/g, "-")}.spec.ts`;
    await writeFile(path.join(generatedDir, fileName), testFile);
    files.push(`tests/generated/${fileName}`);
  }

  return { files, manifest };
}

function generateTestFile(
  scenario: ValidatedScenario,
  suite: ValidatedSuite,
): string {
  const lines: string[] = [];
  lines.push(
    "// GENERATED BY FORGE — do not edit by hand. Machine-owned path.",
  );
  lines.push(`// capability: ${suite.capabilityName}`);
  lines.push(`// plan: ${suite.planId} round ${suite.round}`);
  lines.push(`// scenarios: ${suite.scenarios.map((s) => s.id).join(" ")}`);
  lines.push("");
  lines.push(`import { test, expect } from "../fixtures/forge";`);
  lines.push("");
  lines.push(`test.describe("${escapeForJs(scenario.title)}", () => {`);
  lines.push(
    `  test("${scenario.id} ${escapeForJs(scenario.title)}", async ({ page, forgePage }) => {`,
  );

  for (const step of scenario.steps) {
    if (step.kind === "navigate") {
      lines.push(
        `    await forgePage.goto("${escapeForJs(step.targetIntent)}");`,
      );
    } else if (step.kind === "click") {
      lines.push(
        `    await forgePage.locator("${escapeForJs(step.locator ?? "")}").click();`,
      );
    } else if (step.kind === "fill") {
      lines.push(
        `    await forgePage.locator("${escapeForJs(step.locator ?? "")}").fill("${escapeForJs(step.input ?? "")}");`,
      );
    } else if (step.kind === "select") {
      lines.push(
        `    await forgePage.locator("${escapeForJs(step.locator ?? "")}").selectOption("${escapeForJs(step.input ?? "")}");`,
      );
    } else if (step.kind === "press") {
      lines.push(
        `    await forgePage.locator("${escapeForJs(step.locator ?? "")}").press("${escapeForJs(step.input ?? "")}");`,
      );
    } else if (step.kind === "hover") {
      lines.push(
        `    await forgePage.locator("${escapeForJs(step.locator ?? "")}").hover();`,
      );
    } else if (step.kind === "assertText") {
      lines.push(
        `    await expect(forgePage.locator("${escapeForJs(step.locator ?? "")}")).toHaveText("${escapeForJs(step.input ?? "")}");`,
      );
    } else if (step.kind === "assertVisible") {
      lines.push(
        `    await expect(forgePage.locator("${escapeForJs(step.locator ?? "")}")).toBeVisible();`,
      );
    } else if (step.kind === "assertUrl") {
      lines.push(
        `    await expect(forgePage).toHaveURL("${escapeForJs(step.input ?? "")}");`,
      );
    } else if (step.kind === "assertCount") {
      lines.push(
        `    await expect(forgePage.locator("${escapeForJs(step.locator ?? "")}")).toHaveCount(${step.input ?? "1"});`,
      );
    }
  }

  lines.push("  });");
  lines.push("});");
  return lines.join("\n") + "\n";
}

function escapeForJs(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

async function writeFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf-8");
}
