import type { TestStep } from "../schema/index.js";
import { assertLines, isAssertion } from "./assert.js";
import type { LocatorSpec } from "./locate.js";
import type { CompiledScenario, CompiledStep, CompileContext } from "./types.js";

/** Render action + assertion lines for one step. */
export function renderStep(
  step: TestStep,
  locatorExpr: string | null,
  locatorSpec: LocatorSpec | null,
  ctx: CompileContext,
): CompiledStep {
  const lines: string[] = [];

  if (step.kind === "navigate") {
    const path =
      locatorSpec?.strategy === "goto"
        ? locatorSpec.path
        : pathnameOf(ctx.stateUrlById.get(step.stateId) ?? step.input ?? "/");
    lines.push(`await page.goto(${JSON.stringify(path)});`);
  } else if (isAssertion(step.kind)) {
    lines.push(...assertLines(step, locatorExpr, ctx.stateUrlById.get(step.stateId)));
  } else if (locatorExpr !== null) {
    lines.push(...actionLines(step, locatorExpr));
  }

  return {
    stepId: step.id,
    order: step.order,
    kind: step.kind,
    locatorExpr,
    locatorSpec,
    input: step.input,
    lines,
  };
}

function actionLines(step: TestStep, locatorExpr: string): string[] {
  const target = `page.${locatorExpr}`;
  switch (step.kind) {
    case "click":
      return [`await ${target}.click();`];
    case "fill":
      return [`await ${target}.fill(${inputExpr(step.input)});`];
    case "select":
      return [`await ${target}.selectOption(${inputExpr(step.input)});`];
    case "press":
      return [`await ${target}.press(${inputExpr(step.input ?? "Enter")});`];
    case "hover":
      return [`await ${target}.hover();`];
    case "waitFor":
      return [`await ${target}.waitFor({ state: "visible" });`];
    default:
      return [];
  }
}

/** `$FORGE_TEST_CARD` → `process.env.FORGE_TEST_CARD!`; otherwise a string literal. */
function inputExpr(input: string | null): string {
  if (input === null) return '""';
  const env = /^\$([A-Z][A-Z0-9_]*)$/.exec(input);
  if (env) return `process.env.${env[1]}!`;
  return JSON.stringify(input);
}

function pathnameOf(url: string): string {
  try {
    return new URL(url).pathname;
  } catch {
    return url.startsWith("/") ? url : `/${url}`;
  }
}

export function renderSpecFile(
  capabilityName: string,
  capabilityId: string,
  planId: string,
  round: number,
  assessmentScore: number,
  floor: number,
  scenarios: CompiledScenario[],
  scenarioIds: string[],
): string {
  const header = [
    "// GENERATED BY FORGE — do not edit by hand. Machine-owned path (FR-407).",
    `// capability: ${capabilityId} ${JSON.stringify(capabilityName)}`,
    `// plan:       ${planId} round ${round} · assessment score ${formatScore(assessmentScore)} · floor ${formatScore(floor)}`,
    `// scenarios:  ${scenarioIds.join(" ")}`,
  ].join("\n");

  const body = scenarios.map((scenario) => renderScenario(scenario)).join("\n\n");

  return [
    header,
    'import { test, expect } from "@playwright/test";',
    "",
    `test.describe(${JSON.stringify(capabilityName)}, () => {`,
    indent(body, 2),
    "});",
    "",
  ].join("\n");
}

function renderScenario(scenario: CompiledScenario): string {
  const lines = scenario.steps.flatMap((s) => s.lines);
  const title = `[${scenario.scenarioId}] ${scenario.title}`;
  return [
    `test(${JSON.stringify(title)}, async ({ page }) => {`,
    ...lines.map((line) => `  ${line}`),
    "});",
  ].join("\n");
}

function formatScore(n: number): string {
  // Provenance header uses fixed decimals — never wall-clock ([12 §7]).
  return n.toFixed(4);
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length === 0 ? line : pad + line))
    .join("\n");
}

export function slugCapability(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
