import { z } from "zod";
import { Id, Iso, Sha256 } from "./primitives.js";

export const SessionEventType = z.enum([
  "session.started",
  "explore.state",
  "explore.finished",
  "capabilities.ranked",
  "lap.started",
  "plan.drafted",
  "critique.finished",
  "critique.replan",
  "generate.validated",
  "generate.dropped",
  "run.started",
  "step.finished",
  "evidence.captured",
  "lap.banked",
  "report.generated",
  "session.finished",
]);
export const SessionEvent = z.object({
  id: Id,
  eventVersion: z.literal(1),
  seq: z.number().int().nonnegative(),
  sessionId: Id,
  lapId: Id.nullable(),
  at: Iso,
  actor: z.enum([
    "orchestrator",
    "explorer",
    "planner",
    "critic",
    "generator",
    "runner",
    "triage",
    "healer",
    "reporter",
    "human",
  ]),
  type: SessionEventType,
  payload: z.record(z.unknown()),
  evidenceIds: z.array(Id).default([]),
  traceId: z.string(),
  spanId: z.string(),
  configSha256: Sha256,
});
export const Evidence = z.object({
  id: Id,
  sessionId: Id,
  lapId: Id.nullable(),
  runId: Id.nullable(),
  stepId: z.string().nullable(),
  type: z.enum([
    "SNAPSHOT",
    "DOM",
    "SCREENSHOT",
    "CROP",
    "TRACE",
    "CONSOLE",
    "NETWORK",
    "DIFF",
    "PATCH",
    "TRANSCRIPT",
    "PLAN",
    "REPORT",
  ]),
  path: z.string(),
  sha256: Sha256,
  bytes: z.number().int().nonnegative(),
  capturedAt: Iso,
  label: z.string(),
  metadata: z.record(z.unknown()).default({}),
});
export type SessionEvent = z.infer<typeof SessionEvent>;
export type Evidence = z.infer<typeof Evidence>;
